[package]
name = "rnet_serde"
version = "0.1.0"
authors = ["gpoblon <gpoblon@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnet_serde_derive = { path = "../rnet_serde_derive", version = "0.1.0" }